AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'spec/spec_helper.rb'
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/seeds.rb'
