services:
  - type: web
    name: istos-staging
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: LANG # Imported from Heroku app
        value: en_US.UTF-8
      - key: RACK_ENV # Imported from Heroku app
        value: production
      - key: RAILS_ENV # Imported from Heroku app
        value: production
      - key: RAILS_LOG_TO_STDOUT # Imported from Heroku app
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES # Imported from Heroku app
        value: enabled
