name: CI

on: [ push, pull_request ]

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3

    - name: Setup test database
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        RAILS_ENV: test
      run:
        bundle exec rake db:create db:migrate

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        RAILS_ENV: test
      run: bundle exec rake spec
